name: CICD Pipeline

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch: 

jobs:
  code:
    uses: ./.github/workflows/code.yml # workflow called
  build:
    needs: code
    uses: ./.github/workflows/build.yml
  test:
    needs: build
    uses: ./.github/workflows/test.yml
  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
